Add C-M non-prefixed bindings

diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,27 +18,27 @@ from_repo() {
 }
 
 main() {
-	declare script_name=$0
-	local dir
+  declare script_name=$0
+  local dir
 
-	mkdir -p ~/.tmux/plugins/
+  mkdir -p ~/.tmux/plugins/
 
-	dir="$(cd "$(dirname "${script_name}")" && pwd)"
-	if [[ "$(basename "${dir}")" == "bin" ]]; then
-		dir="$(cd "${dir}"/.. && pwd)"
-	fi
+  dir="$(cd "$(dirname "${script_name}")" && pwd)"
+  if [[ "$(basename "${dir}")" == "bin" ]]; then
+    dir="$(cd "${dir}"/.. && pwd)"
+  fi
 
-	if [[ -f ~/.tmux.conf && "$(readlink -f ~/.tmux.conf)" != "$dir/tmux.conf" ]]; then
-		echo -n "Existing ~/.tmux.conf found. Overwrite? (y/N) "
-		read -r response
-		if [[ "${response}" == "y" ]]; then
-			rm -f ~/.tmux.conf
-		else
-			echo "${RED}Installation aborted.${END_COLOR}"
-			exit 1
-		fi
+  if [[ -f ~/.tmux.conf && "$(readlink -f ~/.tmux.conf)" != "$dir/tmux.conf" ]]; then
+    echo -n "Existing ~/.tmux.conf found. Overwrite? (y/N) "
+    read -r response
+    if [[ "${response}" == "y" ]]; then
+      rm -f ~/.tmux.conf
+    else
+      echo "${RED}Installation aborted.${END_COLOR}"
+      exit 1
+    fi
 
-	fi
+  fi
 
   if ! from_repo "${dir}"; then
     echo "tmuxfiles repository not yet cloned. Cloning..."
@@ -46,17 +46,17 @@ main() {
     git clone "${TMUXFILES_REPO_URL}" "${dir}"
   fi
 
-	if [[ ! -L ~/.tmux.conf ]]; then
-		ln -s "${dir}/tmux.conf" ~/.tmux.conf
-	fi
+  if [[ ! -L ~/.tmux.conf ]]; then
+    ln -s "${dir}/tmux.conf" ~/.tmux.conf
+  fi
 
-	if [[ ! -d ~/.tmux/plugins/tpm ]]; then
-		git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
-	fi
+  if [[ ! -d ~/.tmux/plugins/tpm ]]; then
+    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+  fi
 
-	~/.tmux/plugins/tpm/bin/install_plugins
-	~/.tmux/plugins/tpm/bin/update_plugins all
-	~/.tmux/plugins/tpm/bin/clean_plugins
+  ~/.tmux/plugins/tpm/bin/install_plugins
+  ~/.tmux/plugins/tpm/bin/update_plugins all
+  ~/.tmux/plugins/tpm/bin/clean_plugins
 }
 
 main "$@"
